disabled_rules: 
  - colon
  - comma
  - control_statement
  - force_cast
  - force_try
  - identifier_name
  - implicit_getter
  - line_length
  - multiple_closures_with_trailing_closure
  - nesting
  - type_name
included: 
  - Sources
analyzer_rules:
  - explicit_self
type_body_length:
  - 300 # warning
  - 400 # error
file_length:
  warning: 500
  error: 1200
reporter: "xcode"
